# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe1b55b567ec71c9657de461b100d395fadee082dcd8fcd7f3f4bea44e4d037f15c66aaf6316a4c989a23ee736691e10cfd8bd299cfefdd91e4913382bb977bf

test:
  secret_key_base: 63b335a75fb0389e1e083ef8c3d7a0068c5033bcdf48b67d9ee57f75b2db12e74e014b327c4eab7c30e7f0f3333077ba1baf49e4c1e8f94239044a19816c5e97

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
